//File for the managing of more information of places in the app
export default class MoreInfoManager {
    static myInstance = null;
    //The info value for each piece of information in the app
    infoValue = "";

    //List of all information of all places in the app
    allInfo = [
        {
            infoNum: 1,
            title: "Firedoor",
            subtitle: "23-33 Mary St, Surry Hills NSW 2010, Australia",
            image: require('../assets/Firedoor-Info.jpg'),
            imageCard: require('../assets/Firedoor.jpg'),
            logo: require('../assets/Firedoor-Logo.png'),
            logoHeight: 50,
            logoWidth: 450,
            detail: "Firedoor is the only fully wood fueled restaurant in Australia and is co-owned by chef\
            Lennox Hastie. It was opened in 2015 with the Fink Group and has a fire-only menu with all flavoring to the food coming from the various types of wood used for the cooking. Firedoor is located in Surry Hills, Sydney, Australia. In 2018,\
            the restaurant won the inaugural Rare Medium Award from the Financial Review Australia's Top\
            100 Restaurants guide. That year it also received the Hot Talent Award at the Time Out Food Awards 2018. It was rated by the\
            World Best Steaks as the number one restaurant choice for 2019/2020. It was chosen\
            in 2020 as a Gault&Millau Australia TOP 100 restaurant. It was rated by Discovery as one of the world's 50 best restaurants. The restaurant was featured in the Netflix documentary series Chef's Table: BBQ which aired on September 2, 2020.",
            link: "https://www.firedoor.com.au",
            category:"Restaurant",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 2,
            title: "Quay",
            subtitle: "Upper Level Overseas Passenger Terminal, The Rocks NSW 2000, Australia",
            image: require('../assets/Quay-Info.jpg'),
            imageCard: require('../assets/Quay.jpg'),
            logo: require('../assets/Quay-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "Quay is a restaurant in Sydney, Australia.\
            It is owned by Leon Fink, and is run by chef\
            Peter Gilmore. It has won several awards in\
            Australia, and has appeared in The World's 50\
            Best Restaurants several times. Quay serves\
            contemporary Australian cuisine. The restaurant\
            has several signature dishes, including the\
            'Snow Egg', an egg-shaped poached meringue\
            with an ice cream centre, which is coated in\
            a sweet tuile by using a blow torch. It is served\
            on a bed of fruit fool and granita. The 'Snow\
            Egg' was re-created in the finale of the 2010\
            series of MasterChef Australia and after\
            achieving cult status was phased out in 2018.\
            Another signature dish is Gilmore's 'Eight-\
            Textured Chocolate Cake', which in an earlier\
            version included only five different textures, but was subsequently developed and now contains eight.",
            link: "https://www.quay.com.au",
            category:"Restaurant",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 3,
            title: "Art Gallery NSW",
            subtitle: "Art Gallery Rd, Sydney NSW 2000, Australia",
            image: require('../assets/Art-Gallery-NSW-Info.jpg'),
            imageCard: require('../assets/Art-GalleryNSW.jpg'),
            logo: require('../assets/Art-Gallery-NSW-Logo.png'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "The Art Gallery of New South Wales (AGNSW), founded as the New South Wales Academy of Art in 1872 and known as the National Art Gallery of New South Wales between 1883 and 1958, is located in The Domain in Sydney, New South Wales, Australia. It is the most important public gallery in Sydney and one of the largest in Australia. The Gallery's first public exhibition opened in 1874. Admission is free to the general exhibition space, which displays Australian art (including Indigenous Australian art), European and Asian art. A dedicated Asian Gallery was opened in 2003.",
            link: "https://www.artgallery.nsw.gov.au",
            category:"Museum",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 4,
            title: "State Library of NSW",
            subtitle: "1 Shakespeare Pl, Sydney NSW 2000, Australia",
            image: require('../assets/State-Library-NSW-Info.jpg'),
            imageCard: require('../assets/State-Library-NSW.jpg'),
            logo: require('../assets/State-Library-NSW-Logo.png'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "The State Library of New South Wales, part of which is known as the Mitchell Library, is a large heritage-listed special collections, reference and research library open to the public. It is the oldest library in Australia, being the first established in the colony of New South Wales (now a state of Australia) in 1826. The library is located on the corner of Macquarie Street and Shakespeare Place, in the Sydney central business district adjacent to the Domain and the Royal Botanic Gardens, in the City of Sydney, New South Wales, Australia. The library is a member of the National and State Libraries Australia (NSLA) consortium. The State Library of New South Wales building was designed by Walter Liberty Vernon, assisted by H. C. L. Anderson and was built from 1905 to 1910, with further additions by Howie Bros in 1939; by FWC Powell & Sons in 1959; and by Mellocco Bros in 1964. The property was added to the New South Wales State Heritage Register on 2 April 1999.",
            link: "https://www.sl.nsw.gov.au",
            category:"Library",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 5,
            title: "Park Hyatt Sydney",
            subtitle: "7 Hickson Road, The Rocks, Sydney NSW 2000, Australia",
            image: require('../assets/Park-Hyatt-Sydney-Info.jpg'),
            imageCard: require('../assets/Park-Hyatt-Sydney.jpg'),
            logo: require('../assets/Park-Hyatt-Sydney-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 400,
            detail: "The newly designed Park Hyatt Sydney brings a new level of contemporary luxury to the edge of Sydney Harbour with its waterfront location and spectacular views of the famous Harbour Bridge and Sydney Opera House. Located in the historic Rocks district, it is just a few minutes away from the central business, cultural, and shopping districts of Sydney. Designed to celebrate the property's unique indoor-outdoor experience, guest rooms feature floor-to-ceiling glass doors that open onto private balconies, honoring the hotel’s exclusive waterfront location. The redesigned restaurant and bar on-site offer a quintessentially Sydney dining experience, whilst the introduction of The Living Room provides guests with a comfortable and elegant setting to enjoy refreshments throughout the day.",
            link: "https://www.hyatt.com/en-US/hotel/australia/park-hyatt-sydney/sydph",
            category:"Hotel",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 6,
            title: "Teranga",
            subtitle: "1280 5th Ave, New York, NY 10029, USA",
            image: require('../assets/Teranga-Info.jpg'),
            imageCard: require('../assets/Teranga-NY.jpg'),
            logo: require('../assets/Teranga-Logo.png'),
            logoHeight: 100,
            logoWidth: 400,
            detail: "Rooted in traditional African home cooking that emphasizes African-grown ingredients, Teranga is a culinary journey into the depth, diversity, and deliciousness that the motherland has to offer.  In Senegal, “Teranga” is perhaps the most highly regarded value.  Roughly translated, it means “good hospitality.”  In practice, Teranga reflects how one treats a guest—with open arms and a seat around the bowl.  Teranga’s menu is created by Executive Chef and Co-Founder, Pierre Thiam.",
            link: "https://itsteranga.com/home",
            category:"Restaurant",
            country:"America",
            city:"New York",
        },
        {
            infoNum: 7,
            title: "St Patrick's Church",
            subtitle: "20 Grosvenor St, The Rocks NSW 2000, Australia",
            image: require('../assets/St-Patrick-Info.jpg'),
            imageCard: require('../assets/St-Patrick-Church-Sydney.jpg'),
            logo: require('../assets/St-Patrick-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 400,
            detail: "The St Patrick's Catholic Church is an active Catholic church building located at the junction of Grosvenor and Gloucester Streets in the inner city Sydney suburb of The Rocks in the City of Sydney local government area of New South Wales, Australia. It was designed by William Fernyhough and John Frederick Hilly and built from 1840 to 1844 by Andrew Ross & Co. It is also known as St Patrick's, Church Hill and St Pat's Church Hill. The property is owned by the Trustees of the Roman Catholic Archdiocese of Sydney. The Marist Fathers, a religious order, have administered the parish since 1868. The church is associated with the heritage-listed Federation Hall located at 24-30 Grosvenor Street, built as a parish hall and was used for that purpose until 1914. The property was sold by the parish in the 1920s.",
            link: "https://stpatschurchhill.org",
            category:"Church",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 8,
            title: "Queen Victoria Building",
            subtitle: "1455 George St, Sydney NSW 2000, Australia",
            image: require('../assets/Queen-Victoria-Building-Info.jpg'),
            imageCard: require('../assets/Queen-Victoria-Building-Sydney.jpg'),
            logo: require('../assets/Queen-Victoria-Building-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 200,
            detail: "The Queen Victoria Building (abbreviated as the QVB) is a heritage-listed late-nineteenth-century building designed by the architect George McRae located at 429–481 George Street in the Sydney central business district, in the Australian state of New South Wales. The Romanesque Revival building was constructed between 1893 and 1898 and is 30 metres (98 ft) wide by 190 metres (620 ft) long. The domes were built by Ritchie Brothers, a steel and metal company that also built trains, trams and farm equipment. The building fills a city block bounded by George, Market, York and Druitt Streets. Designed as a marketplace, it was used for a variety of other purposes, underwent remodelling and suffered decay until its restoration and return to its original use in the late twentieth century. The property is owned by the City of Sydney and was added to the New South Wales State Heritage Register on 5 March 2010.",
            link: "https://www.qvb.com.au",
            category:"Mall",
            country:"Australia",
            city:"Melbourne",
        },
        {
            infoNum: 9,
            title: "Bondi Farmers Market",
            subtitle: "Campbell Parade, Bondi Beach NSW 2026, Australia",
            image: require('../assets/Bondi-Farmers-Market-Info.jpg'),
            imageCard: require('../assets/Bondi-Farmers-Market.png'),
            detail: "The Bondi Farmers Market is held every Saturday at Bondi Beach Public School. The market brings you fresh seasonal fruit and vegetables, organically grown meat and poultry, just picked flowers, artisan breads, homemade jams, farmstead cheeses, seafood, olive oils, herbs, spices, and much more.",
            link: "http://bondimarkets.com.au/farmers/",
            category:"Market",
            country:"Australia",
            city:"Sydney",
        },
        {
            infoNum: 10,
            title: "Element Melbourne Richmond",
            subtitle: "588 Swan St, Richmond VIC 3121, Australia",
            image: require('../assets/Element-Melbourne-Richmond-Info.jpg'),
            imageCard: require('../assets/Element-Melbourne-Richmond.jpg'),
            logo: require('../assets/Element-Melbourne-Richmond-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 120,
            detail: "Element Melbourne Richmond, located in the Richmond area, is a popular choice for travelers. From here, guests can make the most of all that the lively city has to offer. With its convenient location, the property offers easy access to the city's must-see destinations. Marriott is renowned for its quality services and friendly staff, and Element Melbourne Richmond lives up to expectations. This property offers numerous on-site facilities to satisfy even the most discerning guest.",
            link: "https://www.marriott.com/hotels/travel/melel-element-melbourne-richmond/",
            category:"Hotel",
            country:"Australia",
            city:"Melbourne",
        },
        {
            infoNum: 11,
            title: "Royal Botanic Garden",
            subtitle: "Melbourne VIC 3004, Australia",
            image: require('../assets/Royal-Botanic-Garden-Info.jpg'),
            imageCard: require('../assets/Royal-Botanic-Garden-Victoria.jpg'),
            logo: require('../assets/Royal-Botanic-Garden-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "Royal Botanic Gardens Victoria are botanic gardens across two sites - Melbourne and Cranbourne. Melbourne Gardens was founded in 1846 when land was reserved on the south side of the Yarra River for a new botanic garden. It extends across 38 hectares (94 acres) that slope to the river with trees, garden beds, lakes and lawns.",
            link: "https://www.rbg.vic.gov.au",
            category:"Park",
            country:"Australia",
            city:"Melbourne",
        },
        {
            infoNum: 12,
            title: "Emporium Melbourne",
            subtitle: "287 Lonsdale St, Melbourne VIC 3000, Australia",
            image: require('../assets/Emporium-Melbourne-Info.jpg'),
            imageCard: require('../assets/Emporium-Melbourne.jpg'),
            logo: require('../assets/Emporium-Melbourne-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "Emporium Melbourne (or simply Emporium) is a luxury shopping centre on the corner of Lonsdale and Swanston streets in Melbourne, Australia. Occupying the former Lonsdale Street site of Myer's Melbourne store, Emporium opened in 2014 following extensive redevelopment. The centre includes a food court, specialty stores and several multi-level anchor retailers, as well as a top floor extension of Myer's Bourke Street store. Emporium forms part of a 188,000 square metres (2,020,000 sq ft) precinct of linked shopping centres in the Melbourne CBD, which also includes the Myer and David Jones city stores, Melbourne Central, GPO and Elizabeth Street's The Strand.",
            link: "https://www.emporiummelbourne.com.au",
            category:"Mall",
            country:"Australia",
            city:"Melbourne",
        },
        {
            infoNum: 13,
            title: "Prahran Market",
            subtitle: "163 Commercial Rd, South Yarra VIC 3141, Australia",
            image: require('../assets/Prahran-Info.jpg'),
            imageCard: require('../assets/Prahran-Market.jpg'),
            logo: require('../assets/Prahran-Logo.png'),
            logoHeight: 100,
            logoWidth: 200,
            detail: "Prahran Market is a food market in South Yarra, an inner suburb of Melbourne, Victoria, Australia. Located on Commercial Road near Chapel Street, it was established in neighbouring Prahran in the 1860s before moving to its present location in 1881. The market has a variety of stalls and specialty shops selling fresh fruit and vegetables, meat, fish and deli foods, as well as cafes. The market is open every day except Mondays and Wednesdays, with select traders operating on Sundays.",
            link: "https://www.prahranmarket.com.au",
            category:"Market",
            country:"Australia",
            city:"Melbourne",
        },
        {
            infoNum: 14,
            title: "Romeo Lane",
            subtitle: "1A Crossley St, Melbourne VIC 3000, Australia",
            image: require('../assets/Romeo-Lane-Info.jpg'),
            imageCard: require('../assets/Romeo-Lane.jpg'),
            logo: require('../assets/Romeo-Lane-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 200,
            detail: "Romeo Lane serves classic cocktails from midday along with inventive, seasonal small plates and more old-world charm than you can poke a stick at. First-time business owners Joe Jones and Rita Ambroz both come from a healthy stint at nearby Lily Blacks, and as a consequence certainly know their way around a Boston shaker. While they admit to enjoying Prohibition era-style alcoholic concoctions, both are big fans of traditional European-style cocktails, which means you’ll see plenty of sherry, gin and top-shelf cognac on the drinks list.",
            link: "https://www.romeolane.com.au",
            category:"Bar",
            country:"Australia",
            city:"Melbourne",
        },
        {
            infoNum: 15,
            title: "Africola",
            subtitle: "4 East Terrace, Adelaide SA 5000, Australia",
            image: require('../assets/Africola-Info.jpg'),
            imageCard: require('../assets/Africola.jpg'),
            logo: require('../assets/Africola-Logo.png'),
            logoHeight: 100,
            logoWidth: 400,
            detail: "Africola good times can now be delivered to your door. Buy Africola gold on Uber Eats African restaurant located on east terrace, Adelaide. Compact, simple shop with a western soundtrack, African-inspired vegetables, grilled and smoked meats, flatbreads, pickles and natural wine. Blowing up like bubblegum. Africola living. We buy gold. We smoke then baste our foods in their own juices. Our menu changes regularly to reflect seasonality.",
            link: "https://www.africola.com.au",
            category:"Restaurant",
            country:"Australia",
            city:"Adelaide",
        },
        {
            infoNum: 16,
            title: "Crowne Plaza",
            subtitle: "7 Frome St, Adelaide SA 5000, Australia",
            image: require('../assets/Crowne-Plaza-Info.jpg'),
            imageCard: require('../assets/Crowne-Plaza.jpg'),
            logo: require('../assets/Crowne-Plaza-Logo.png'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "Stay in the City’s East End, an iconic Adelaide cultural, retail and culinary hub; only 20 minutes from Adelaide Airport.  Located across from Lot Fourteen and a tram ride away from the Adelaide Oval, Adelaide Convention Centre and the Adelaide Casino. Park onsite and choose from 329 design-led guest rooms starting from 28 square meters, with a flexible workspace, separate walk-in shower, floor-to-ceiling windows, free WIFI, Sleep Advantage Program and to get you going, an espresso capsule machine. Make every meeting a success with a dedicated Crowne Meetings Manager, 450 square meters of flexible meeting space, easy on-demand audio visual technology plus energising F&B packages.",
            link: "https://adelaide.crowneplaza.com",
            category:"Hotel",
            country:"Australia",
            city:"Adelaide",
        },
        {
            infoNum: 17,
            title: "British Museum",
            subtitle: "Great Russell St, Bloomsbury, London WC1B 3DG, England",
            image: require('../assets/British-Museum-Info.jpg'),
            imageCard: require('../assets/British-Museum.jpg'),
            logo: require('../assets/British-Museum-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "The British Museum, in the Bloomsbury area of London, England, is a public institution dedicated to human history, art and culture. Its permanent collection of some eight million works is among the largest and most comprehensive in existence, having been widely collected during the era of the British Empire. It documents the story of human culture from its beginnings to the present. It was the first public national museum in the world.",
            link: "https://www.britishmuseum.org",
            category:"Museum",
            country:"England",
            city:"London",
        },
        {
            infoNum: 18,
            title: "The Egerton House",
            subtitle: "17-19 Egerton Terrace, Chelsea, London SW3 2BX, England",
            image: require('../assets/Egerton-House-Info.jpg'),
            imageCard: require('../assets/Egerton-House.jpg'),
            logo: require('../assets/Egerton-House-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 200,
            detail: "Egerton House Hotel is an AA five star double-townhouse hotel located at 17-19 Egerton Terrace off Brompton Road in the Knightsbridge area of London. It is part of the Red Carnation Hotels group. The hotel consists of two adjoining Victorian townhouses constructed from red-brick, which were originally built in 1843. It is managed by Michelle Devlin and Annie McCrann. The hotel has 28 en-suite rooms and a number of suites. The hotel is consistently rated within the top 10 best reviewed hotels within London on Tripadvisor.com",
            link: "https://egertonhousehotel.com",
            category:"Hotel",
            country:"England",
            city:"London",
        },
        
        {
            infoNum: 19,
            title: "British Library",
            subtitle: "96 Euston Rd, Somers Town, London NW1 2DB, England",
            image: require('../assets/British-Library-Info.jpg'),
            imageCard: require('../assets/British-Library.jpg'),
            logo: require('../assets/British-Library-Logo.png'),
            logoHeight: 80,
            logoWidth: 400,
            detail: "The British Library is the national library of the United Kingdom and is one of the largest libraries in the world. It is estimated to contain between 170–200 million items from many countries. As a legal deposit library, the British Library receives copies of all books produced in the United Kingdom and Ireland, including a significant proportion of overseas titles distributed in the UK. The Library is a non-departmental public body sponsored by the Department for Digital, Culture, Media and Sport.",
            link: "https://www.bl.uk",
            category:"Library",
            country:"England",
            city:"London",
        },
        
        {
            infoNum: 20,
            title: "Coal Drops Yard",
            subtitle: "Stable St, Kings Cross, London N1C 4DQ, England",
            image: require('../assets/Coal-Drops-Yard-Info.jpg'),
            imageCard: require('../assets/Coal-Drops-Yard.jpg'),
            detail: "Coal Drops Yard is a shopping complex and privately owned public space that forms part of the King's Cross Central development scheme in London, England. The development was designed by Thomas Heatherwick and opened in October 2018.",
            link: "https://www.coaldropsyard.com",
            category:"Mall",
            country:"England",
            city:"London",
        },
        
        {
            infoNum: 21,
            title: "Library of Birmingham",
            subtitle: "Centenary Square, Broad St, Birmingham B1 2EA, England",
            image: require('../assets/Library-Birmingham-Info.jpg'),
            imageCard: require('../assets/Library-Birmingham.jpg'),
            logo: require('../assets/Library-Birmingham-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 150,
            detail: "The Library of Birmingham is a public library in Birmingham, England. It is situated on the west side of the city centre at Centenary Square, beside the Birmingham Rep (to which it connects, and with which it shares some facilities) and Baskerville House. Upon opening on 3 September 2013, it replaced Birmingham Central Library. The library, which is estimated to have cost £188.8 million, is viewed by the Birmingham City Council as a flagship project for the city's redevelopment. It has been described as the largest public library in the United Kingdom, the largest public cultural space in Europe, and the largest regional library in Europe. 2,414,860 visitors came to the library in 2014 making it the 10th most popular visitor attraction in the UK.",
            link: "https://www.birmingham.gov.uk/libraries",
            category:"Library",
            country:"England",
            city:"Birmingham",
        },
        {
            infoNum: 22,
            title: "Birmingham Wholesale Market",
            subtitle: "The Hub, Nobel Wy., Birmingham B6 7EU, England",
            image: require('../assets/Birmingham-Wholesale-Market-Info.jpg'),
            imageCard: require('../assets/Birmingham-Wholesale-Market.jpg'),
            logo: require('../assets/Birmingham-Wholesale-Market-Logo.png'),
            logoHeight: 70,
            logoWidth: 400,
            detail: "Birmingham Wholesale Market is one of the largest integrated wholesale markets in Europe, providing fresh produce to restaurants, hotels, fast food outlets and local retailers across the Midlands and Wales.",
            link: "https://birminghamwholesalemarket.company",
            category:"Market",
            country:"England",
            city:"Birmingham",
        },
        {
            infoNum: 23,
            title: "Spotlight",
            subtitle: "The Hub, Nobel Wy., Birmingham B6 7EU, England",
            image: require('../assets/Spotlight-Info.jpg'),
            imageCard: require('../assets/Spotlight.jpg'),
            detail: "Spotlight is a quirky single room bar & event space built underneath one of Digbeth’s many Victorian Railway Arches. With cherry red leather chesterfield sofas and sturdy steel bar stools, tables and chairs Spotlight is a comfortable place to hang out despite it’s Industrial feel. The various pieces of art around the venue give Spotlight the feel of a venue that wouldn’t be out of place in London’s trendy Shoreditch. Spotlight has cemented it’s place as the #1 after work destination in Birmingham on a Friday with “Digbeth Dining Club” which recently won Best Street Food Event at the British Street Food Awards.",
            link: "https://www.facebook.com/lowertrinitystreet/",
            category:"Bar",
            country:"England",
            city:"Birmingham",
        },
        {
            infoNum: 24,
            title: "The Cloisters",
            subtitle: "99 Margaret Corbin Dr, New York, NY 10040, USA",
            image: require('../assets/The-Cloisters-Info.jpg'),
            imageCard: require('../assets/The-Cloisters-NY.jpg'),
            logo: require('../assets/The-Cloisters-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 150,
            detail: "The Cloisters, also known as the Met Cloisters, is a museum in Fort Tryon Park in Washington Heights, Manhattan, New York City, specializing in European medieval art and architecture, with a focus on the Romanesque and Gothic periods. Governed by the Metropolitan Museum of Art, it contains a large collection of medieval artworks shown in the architectural settings of French monasteries and abbeys. Its buildings are centered around four cloisters—the Cuxa, Saint-Guilhem, Bonnefont and Trie—that were acquired by American sculptor and art dealer George Grey Barnard in France before 1913, and moved to New York. Barnard's collection was bought for the museum by financier and philanthropist John D. Rockefeller, Jr. Other major sources of objects were the collections of J. P. Morgan and Joseph Brummer.",
            link: "https://www.metmuseum.org/visit/plan-your-visit/met-cloisters",
            category:"Museum",
            country:"America",
            city:"New York",
        },
        {
            infoNum: 25,
            title: "Bloomingdale Library",
            subtitle: "150 W 100th St, New York, NY 10025, USA",
            image: require('../assets/Bloomingdale-Library-Info.jpg'),
            imageCard: require('../assets/Bloomingdale-Library.jpg'),
            logo: require('../assets/Bloomingdale-Library-Logo.png'),
            logoHeight: 100,
            logoWidth: 400,
            detail: "The Bloomingdale Public Library has a rich history of progressive thinking and community involvement. From 30 years ago when the Library opened in two mobile classrooms to today's impressive state-of-the-art facility, the residents of Bloomingdale have been instrumental in improving Library services. With financial support, professional development, and time commitments, the Bloomingdale Public Library has evolved to a staff of over 60, providing a variety of services to patrons 68 hours each week in its 35,000 square foot facility.",
            link: "https://www.nypl.org/locations/bloomingdale",
            category:"Library",
            country:"America",
            city:"New York",
        },
        {
            infoNum: 26,
            title: "Westfield World Trade Center",
            subtitle: "185 Greenwich St, New York, NY 10007, USA",
            image: require('../assets/Westfield-World-Trade-Center-Info.jpg'),
            imageCard: require('../assets/Westfield-WorldTrade-Center.jpg'),
            logo: require('../assets/Westfield-World-Trade-Center-Logo.jpg'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "Westfield World Trade Center is a shopping mall at the World Trade Center complex in Manhattan, New York, that is operated and managed by Unibail-Rodamco-Westfield. The mall opened on August 16, 2016 as the largest shopping complex in Manhattan, with 125 retail spaces. It replaces the Mall at the World Trade Center, the underground shopping mall under the original World Trade Center, which was destroyed on September 11, 2001.",
            link: "https://www.westfield.com/westfieldworldtradecenter",
            category:"Mall",
            country:"America",
            city:"New York",
        },
        
        {
            infoNum: 27,
            title: "Leyenda",
            subtitle: "221 Smith St, Brooklyn, NY 11201, USA",
            image: require('../assets/Leyenda-Info.jpg'),
            imageCard: require('../assets/Leyenda-NY.jpg'),
            detail: "Ivy Mix and Julie Reiner are two of the global bartending community's biggest names – they've won everything and worked everywhere. The duo joined forces to create this Latin-inspired neighbourhood cocktail joint. Don't let the laid-back vibes fool you, though, this is a place where you can undergo a full agave education, with a vast selection of the best mezcals and tequilas around – as well as full-on flights to sample an array of the Mexican spirit. Brunch is also a specialty here, taking Mexican fare way beyond tacos and nachos.",
            link: "https://leyendabk.com",
            category:"Bar",
            country:"America",
            city:"New York",
        },
        {
            infoNum: 28,
            title: "Pasjoli",
            subtitle: "2732 Main St, Santa Monica, CA 90405, USA",
            image: require('../assets/Pasjoli-Info.jpg'),
            imageCard: require('../assets/Pasjoli.jpg'),
            detail: "Pasjoli is an elevated French bistro from award-winning chef Dave Beran. The restaurant pays homage to French cuisine utilizing the bounty of produce available in Southern California. Rooted in classic French cuisine and inspired by the Parisian markets, Pasjoli reflects Beran’s thoughtful cooking style, showcasing his creative touches on bistro fare.",
            link: "https://www.pasjoli.com",
            category:"Restaurant",
            country:"America",
            city:"Los Angeles",
        },
        {
            infoNum: 29,
            title: "Getty Center",
            subtitle: "1200 Getty Center Dr, Los Angeles, CA 90049, USA",
            image: require('../assets/Getty-Center-Info.jpg'),
            imageCard: require('../assets/Getty-Center.jpg'),
            logo: require('../assets/Getty-Center-Logo.png'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "Getty is a cultural and philanthropic institution dedicated to the presentation, conservation, and interpretation of the world’s artistic legacy. Through the collective and individual work of its constituent programs—Getty Conservation Institute, Getty Foundation, J. Paul Getty Museum, and Getty Research Institute—Getty pursues its mission in Los Angeles and throughout the world, serving both the general interested public and a wide range of professional communities in order to promote a vital civil society through an understanding of the visual arts.",
            link: "https://www.getty.edu",
            category:"Museum",
            country:"America",
            city:"Los Angeles",
        },
        {
            infoNum: 30,
            title: "Sunset Tower Hotel",
            subtitle: "8358 Sunset Blvd, Los Angeles, CA 90069, USA",
            image: require('../assets/Sunset-Tower-Hotel-Info.jpg'),
            imageCard: require('../assets/Sunset-Tower-Hotel.jpg'),
            logo: require('../assets/Sunset-Tower-Hotel-Logo.png'),
            logoHeight: 100,
            logoWidth: 300,
            detail: "The Sunset Tower Hotel, previously known as The St. James's Club and The Argyle, is a historic building and hotel located on the Sunset Strip in West Hollywood, California. Designed in 1929 by architect Leland A. Bryant, opened in 1931, it is considered one of the finest examples of Art Deco architecture in the Los Angeles area. In its early years, it was the residence of many Hollywood celebrities, including John Wayne and Howard Hughes. After a period of decline in the early 1980s, the building was renovated and has been operated as a luxury hotel under the names The St. James's Club, The Argyle, and most recently the Sunset Tower Hotel. The building was added to the National Register of Historic Places in 1980.",
            link: "https://www.sunsettowerhotel.com",
            category:"Hotel",
            country:"America",
            city:"Los Angeles",
        },
    ];

    //Get an instance of more information
    static getInstance() {
        if(MoreInfoManager.myInstance == null) {
            MoreInfoManager.myInstance = new MoreInfoManager();
        }
        return this.myInstance;
    }

    //Get all information for all places in the app
    getAllInfo() {
        return this.allInfo;
    }

    //Get the info value for any specified one
    getInfoValue() {
        return this.infoValue;
    }

    //Set an info value for any specified one
    setInfoValue({value}) {
        this.infoValue = value;
    }
}