//File for the managing of all places in the app
export default class PlaceManager {
    static myInstance = null;
    //Place number for each one in the places
    placeNumber = "";

    //List of all places in the app
    places = [
        {
            placeNum: 1,
            title: "Firedoor",
            subtitle: "23-33 Mary St, Surry Hills NSW 2010, Australia",
            image: require('../assets/Firedoor.jpg'),
            category:"Restaurant",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 2,
            title: "Quay",
            subtitle: "Upper Level Overseas Passenger Terminal, The Rocks NSW 2000, Australia",
            image: require('../assets/Quay.jpg'),
            category:"Restaurant",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 3,
            title: "Momofuku Seiobo",
            subtitle: "The Star Level G 80 Pyrmont Street Pyrmont, NSW 2009, Australia",
            image: require('../assets/Momofuku-Seiobo.jpg'),
            category:"Restaurant",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 4,
            title: "Art Gallery NSW",
            subtitle: "Art Gallery Rd, Sydney NSW 2000, Australia",
            image: require('../assets/Art-GalleryNSW.jpg'),
            category:"Museum",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 5,
            title: "State Library of NSW",
            subtitle: "1 Shakespeare Pl, Sydney NSW 2000, Australia",
            image: require('../assets/State-Library-NSW.jpg'),
            category:"Library",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 6,
            title: "Park Hyatt Sydney",
            subtitle: "7 Hickson Road, The Rocks, Sydney NSW 2000, Australia",
            image: require('../assets/Park-Hyatt-Sydney.jpg'),
            category:"Hotel",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 7,
            title: "Centennial Park",
            subtitle: "4km South-East of Sydney CBD",
            image: require('../assets/Centennial-Park.jpg'),
            category:"Park",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 8,
            title: "Cantina OK",
            subtitle: "Council Pl, Sydney NSW 2000, Australia",
            image: require('../assets/Cantina-OK.jpg'),
            category:"Bar",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 9,
            title: "Brae",
            subtitle: "4285 Cape Otway Rd, Birregurra VIC 3242, Australia",
            image: require('../assets/Brae-Melbourne.jpg'),
            category:"Restaurant",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 10,
            title: "Teranga",
            subtitle: "1280 5th Ave, New York, NY 10029, USA",
            image: require('../assets/Teranga-NY.jpg'),
            category:"Restaurant",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 11,
            title: "St Patrick's Church",
            subtitle: "120 Grosvenor St, The Rocks NSW 2000, Australia",
            image: require('../assets/St-Patrick-Church-Sydney.jpg'),
            category:"Church",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 12,
            title: "Queen Victoria Building",
            subtitle: "1455 George St, Sydney NSW 2000, Australia",
            image: require('../assets/Queen-Victoria-Building-Sydney.jpg'),
            category:"Mall",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 13,
            title: "Bondi Farmers Market",
            subtitle: "Campbell Parade, Bondi Beach NSW 2026, Australia",
            image: require('../assets/Bondi-Farmers-Market.png'),
            category:"Market",
            country:"Australia",
            city:"Sydney",
        },
        {
            placeNum: 14,
            title: "Melbourne Museum",
            subtitle: "11 Nicholson St, Carlton VIC 3053, Australia",
            image: require('../assets/Melbourne-Museum.jpg'),
            category:"Museum",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 15,
            title: "Element Melbourne Richmond",
            subtitle: "588 Swan St, Richmond VIC 3121, Australia",
            image: require('../assets/Element-Melbourne-Richmond.jpg'),
            category:"Hotel",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 16,
            title: "Royal Botanic Garden",
            subtitle: "Melbourne VIC 3004, Australia",
            image: require('../assets/Royal-Botanic-Garden-Victoria.jpg'),
            category:"Park",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 17,
            title: "State Library Victoria",
            subtitle: "328 Swanston St, Melbourne VIC 3000, Australia",
            image: require('../assets/State-Library-Victoria.jpg'),
            category:"Library",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 18,
            title: "St Paul's Cathedral",
            subtitle: "Flinders St, Melbourne VIC 3000, Australia",
            image: require('../assets/St-Paul-Cathedral.jpg'),
            category:"Church",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 19,
            title: "Emporium Melbourne",
            subtitle: "287 Lonsdale St, Melbourne VIC 3000, Australia",
            image: require('../assets/Emporium-Melbourne.jpg'),
            category:"Mall",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 20,
            title: "Prahran Market",
            subtitle: "163 Commercial Rd, South Yarra VIC 3141, Australia",
            image: require('../assets/Prahran-Market.jpg'),
            category:"Market",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 21,
            title: "Romeo Lane",
            subtitle: "1A Crossley St, Melbourne VIC 3000, Australia",
            image: require('../assets/Romeo-Lane.jpg'),
            category:"Bar",
            country:"Australia",
            city:"Melbourne",
        },
        {
            placeNum: 22,
            title: "Africola",
            subtitle: "4 East Terrace, Adelaide SA 5000, Australia",
            image: require('../assets/Africola.jpg'),
            category:"Restaurant",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 23,
            title: "South Australian",
            subtitle: "North Terrace, Adelaide SA 5000, Australia",
            image: require('../assets/South-Australian-Museum.jpg'),
            category:"Museum",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 24,
            title: "Crowne Plaza",
            subtitle: "27 Frome St, Adelaide SA 5000, Australia",
            image: require('../assets/Crowne-Plaza.jpg'),
            category:"Hotel",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 25,
            title: "Adelaide Botanic Garden",
            subtitle: "North Terrace, Adelaide SA 5000, Australia",
            image: require('../assets/Adelaide-Botanic-Garden.jpg'),
            category:"Park",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 26,
            title: "Trinity Church",
            subtitle: "88 North Terrace, Adelaide SA 5000, Australia",
            image: require('../assets/Trinity-Church.jpg'),
            category:"Church",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 27,
            title: "State Library SA",
            subtitle: "North Terrace &, Kintore Ave, Adelaide SA 5000, Australia",
            image: require('../assets/State-Library-SA.jpg'),
            category:"Library",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 28,
            title: "Adelaide Arcade",
            subtitle: "112/118 Grenfell St, Adelaide SA 5000, Australia",
            image: require('../assets/Adelaide-Arcade.jpg'),
            category:"Mall",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 29,
            title: "Gilles at the Grounds",
            subtitle: "South Blvd, Wayville SA 5034, Australia",
            image: require('../assets/Gilles-At-The-Grounds.jpg'),
            category:"Market",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 30,
            title: "Paloma Bar and Pantry",
            subtitle: "S20 Peel St, Adelaide SA 5000, Australia",
            image: require('../assets/Paloma-Bar.jpg'),
            category:"Bar",
            country:"Australia",
            city:"Adelaide",
        },
        {
            placeNum: 31,
            title: "The Cloisters",
            subtitle: "99 Margaret Corbin Dr, New York, NY 10040, USA",
            image: require('../assets/The-Cloisters-NY.jpg'),
            category:"Museum",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 32,
            title: "Park Hyatt New York",
            subtitle: "153 W 57th St, New York, NY 10019, USA",
            image: require('../assets/Park-Hyatt.jpg'),
            category:"Hotel",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 33,
            title: "Riverside Park",
            subtitle: "Manhattan, New York, NY, USA",
            image: require('../assets/Riverside-Park.jpg'),
            category:"Park",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 34,
            title: "Times Square Church",
            subtitle: "237 W 51st St, New York, NY 10019, USA",
            image: require('../assets/Times-Square-Church.jpg'),
            category:"Church",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 35,
            title: "Bloomingdale Library",
            subtitle: "150 W 100th St, New York, NY 10025, USA",
            image: require('../assets/Bloomingdale-Library.jpg'),
            category:"Library",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 36,
            title: "Westfield World Trade Center",
            subtitle: "185 Greenwich St, New York, NY 10007, USA",
            image: require('../assets/Westfield-WorldTrade-Center.jpg'),
            category:"Mall",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 37,
            title: "Chelsea Market",
            subtitle: "75 9th Ave, New York, NY 10011, USA",
            image: require('../assets/Chelsea-Market.jpg'),
            category:"Market",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 38,
            title: "Leyenda",
            subtitle: "221 Smith St, Brooklyn, NY 11201, USA",
            image: require('../assets/Leyenda-NY.jpg'),
            category:"Bar",
            country:"America",
            city:"New York",
        },
        {
            placeNum: 39,
            title: "Kiln",
            subtitle: "58 Brewer St, Soho, London W1F 9TL, England",
            image: require('../assets/Kiln.png'),
            category:"Restaurant",
            country:"England",
            city:"London",
        },
        {
            placeNum: 40,
            title: "British Museum",
            subtitle: "Great Russell St, Bloomsbury, London WC1B 3DG, England",
            image: require('../assets/British-Museum.jpg'),
            category:"Museum",
            country:"England",
            city:"London",
        },
        {
            placeNum: 41,
            title: "The Egerton House",
            subtitle: "17-19 Egerton Terrace, Chelsea, London SW3 2BX, England",
            image: require('../assets/Egerton-House.jpg'),
            category:"Hotel",
            country:"England",
            city:"London",
        },
        {
            placeNum: 42,
            title: "Hampstead Heath",
            subtitle: "4 miles (6.4 km) northwest of Charing Cross, London, England",
            image: require('../assets/Hampstead-Heath.jpg'),
            category:"Park",
            country:"England",
            city:"London",
        },
        {
            placeNum: 43,
            title: "British Library",
            subtitle: "96 Euston Rd, Somers Town, London NW1 2DB, England",
            image: require('../assets/British-Library.jpg'),
            category:"Library",
            country:"England",
            city:"London",
        },
        {
            placeNum: 44,
            title: "Southwark Cathedral",
            subtitle: "9 London Bridge, London SE1 9DA, England",
            image: require('../assets/Southwark-Cathedral.jpg'),
            category:"Church",
            country:"England",
            city:"London",
        },
        {
            placeNum: 45,
            title: "Coal Drops Yard",
            subtitle: "Stable St, Kings Cross, London N1C 4DQ, England",
            image: require('../assets/Coal-Drops-Yard.jpg'),
            category:"Mall",
            country:"England",
            city:"London",
        },
        {
            placeNum: 46,
            title: "Borough Market",
            subtitle: "Stable St, Kings Cross, London N1C 4DQ, England",
            image: require('../assets/Borough-Market.jpg'),
            category:"Market",
            country:"England",
            city:"London",
        },
        {
            placeNum: 47,
            title: "Adam's",
            subtitle: "New Oxford House, 16 Waterloo St, Birmingham B2 5UG, England",
            image: require('../assets/Adams.jpg'),
            category:"Restaurant",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 48,
            title: "Think Tank",
            subtitle: "Millennium Point, Curzon St, Birmingham B4 7XG, England",
            image: require('../assets/Thinktank.jpg'),
            category:"Museum",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 49,
            title: "The Edgbaston",
            subtitle: "18 Highfield Rd, Birmingham B15 3DU, England",
            image: require('../assets/Edgbaston.jpg'),
            category:"Hotel",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 50,
            title: "Cannon Hill",
            subtitle: "Russell Rd, Moseley, Birmingham B13 8RD, England",
            image: require('../assets/Cannon-Hill-Park.jpg'),
            category:"Park",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 51,
            title: "Library of Birmingham",
            subtitle: "Centenary Square, Broad St, Birmingham B1 2EA, England",
            image: require('../assets/Library-Birmingham.jpg'),
            category:"Library",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 52,
            title: "Bullring & Grand Central",
            subtitle: "Birmingham, B5 4BU, England",
            image: require('../assets/Grand-Central.jpg'),
            category:"Mall",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 53,
            title: "Birmingham Wholesale Market",
            subtitle: "The Hub, Nobel Wy., Birmingham B6 7EU, England",
            image: require('../assets/Birmingham-Wholesale-Market.jpg'),
            category:"Market",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 54,
            title: "Spotlight",
            subtitle: "TLower Trinity St, Deritend, Birmingham B9 4AG, England",
            image: require('../assets/Spotlight.jpg'),
            category:"Bar",
            country:"England",
            city:"Birmingham",
        },
        {
            placeNum: 55,
            title: "Pasjoli",
            subtitle: "2732 Main St, Santa Monica, CA 90405, USA",
            image: require('../assets/Pasjoli.jpg'),
            category:"Restaurant",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 56,
            title: "Getty Center",
            subtitle: "1200 Getty Center Dr, Los Angeles, CA 90049, USA",
            image: require('../assets/Getty-Center.jpg'),
            category:"Museum",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 57,
            title: "Sunset Tower Hotel",
            subtitle: "8358 Sunset Blvd, Los Angeles, CA 90069, USA",
            image: require('../assets/Sunset-Tower-Hotel.jpg'),
            category:"Hotel",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 58,
            title: "Grand Park",
            subtitle: "200 N Grand Ave, Los Angeles CA 90012, USA",
            image: require('../assets/Grand-Park.jpg'),
            category:"Park",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 59,
            title: "Powell Library",
            subtitle: "10740 Dickson Ct, Los Angeles, CA 90095, USA",
            image: require('../assets/Powell-Library.jpg'),
            category:"Library",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 60,
            title: "Westfield Century City",
            subtitle: "10250 Santa Monica Blvd, Los Angeles, CA 90067, USA",
            image: require('../assets/Westfield-Century-City.jpg'),
            category:"Mall",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 61,
            title: "Rose Bowl Flea",
            subtitle: "1001 Rose Bowl Dr, Pasadena, CA 91103, USA",
            image: require('../assets/Rose-Bowl.jpg'),
            category:"Market",
            country:"America",
            city:"Los Angeles",
        },
        {
            placeNum: 62,
            title: "Ototo",
            subtitle: "1360 Allison Ave, Los Angeles, CA 90026, USA",
            image: require('../assets/Ototo.jpg'),
            category:"Bar",
            country:"America",
            city:"Los Angeles",
        },
    ]

    //Get an instance of places
    static getInstance() {
        if(PlaceManager.myInstance == null) {
            PlaceManager.myInstance = new PlaceManager();
        }
        return this.myInstance;
    }

    //Get all places in the app
    getAllPlaces() {
        return this.places;
    }

    //Get the place number for any specified one
    getPlaceNumber() {
        return this.placeNumber;
    }

    //Set the place number for any specified one
    setPlaceNumber({num}) {
        this.placeNumber = num;
    }

    //Add a new place to a list of existing places
    addPlace(place) {
        this.places.push(place);
    }

    filterPlaces(place) {
        this.places = this.places.filter(
            function (item) {
            const itemData = item.title
                ? item.title.toUpperCase()
                : ''.toUpperCase();
            const textData = place.title.toUpperCase();
            return itemData.indexOf(textData) <= -1;
        });
    }
}